export const UNESCO_FIELDS = [
  {
    code: "01",
    label: "Educación",
    subareas: [
      "Formación de docentes y ciencias de la educación",
      "Educación infantil",
      "Educación primaria",
      "Educación secundaria",
      "Educación superior",
      "Educación especial e inclusiva",
      "Pedagogía y didáctica",
      "Tecnología educativa",
    ],
  },
  {
    code: "02",
    label: "Artes y Humanidades",
    subareas: [
      "Bellas artes y artes escénicas",
      "Diseño y artes aplicadas",
      "Cine, fotografía y medios audiovisuales",
      "Música y musicología",
      "Idiomas y lingüística",
      "Literatura y narrativa",
      "Filosofía y ética",
      "Historia",
      "Arqueología y patrimonio",
      "Teología y estudios religiosos",
    ],
  },
  {
    code: "03",
    label: "Ciencias Sociales, Periodismo e Información",
    subareas: [
      "Sociología",
      "Psicología",
      "Ciencias políticas",
      "Economía",
      "Geografía",
      "Periodismo y comunicación",
      "Biblioteconomía y documentación",
      "Antropología",
      "Trabajo social",
      "Relaciones internacionales",
    ],
  },
  {
    code: "04",
    label: "Negocios, Administración y Derecho",
    subareas: [
      "Administración y dirección de empresas",
      "Marketing y ventas",
      "Finanzas y contabilidad",
      "Recursos humanos y gestión de personas",
      "Emprendimiento e innovación",
      "Comercio internacional",
      "Derecho privado",
      "Derecho público y administrativo",
      "Derecho mercantil",
      "Derecho internacional",
    ],
  },
  {
    code: "05",
    label: "Ciencias Naturales, Matemáticas y Estadística",
    subareas: [
      "Matemáticas",
      "Estadística y probabilidad",
      "Física",
      "Química",
      "Biología",
      "Bioquímica",
      "Ciencias del medioambiente",
      "Geología y ciencias de la tierra",
      "Astronomía y astrofísica",
    ],
  },
  {
    code: "06",
    label: "Tecnologías de la Información y Comunicación",
    subareas: [
      "Ingeniería informática y desarrollo de software",
      "Ciencia de datos e inteligencia artificial",
      "Ciberseguridad",
      "Redes y telecomunicaciones",
      "Sistemas de información",
      "Computación en la nube",
      "Interacción persona-computador (UX/UI)",
      "Blockchain y tecnologías emergentes",
    ],
  },
  {
    code: "07",
    label: "Ingeniería, Industria y Construcción",
    subareas: [
      "Ingeniería civil",
      "Ingeniería mecánica",
      "Ingeniería eléctrica y electrónica",
      "Ingeniería química e industrial",
      "Arquitectura y urbanismo",
      "Ingeniería aeronáutica y aeroespacial",
      "Energías renovables",
      "Robótica y automatización",
      "Ingeniería de materiales",
      "Transporte y logística",
    ],
  },
  {
    code: "08",
    label: "Agricultura, Veterinaria y Medioambiente",
    subareas: [
      "Agronomía y producción agrícola",
      "Ciencias forestales",
      "Pesca y acuicultura",
      "Veterinaria y zootecnia",
      "Ecología y biodiversidad",
      "Gestión ambiental y sostenibilidad",
      "Alimentación y nutrición",
    ],
  },
  {
    code: "09",
    label: "Salud y Servicios Sociales",
    subareas: [
      "Medicina y cirugía",
      "Enfermería y cuidados",
      "Farmacia y ciencias farmacéuticas",
      "Odontología",
      "Fisioterapia y rehabilitación",
      "Psicología clínica",
      "Salud pública y epidemiología",
      "Nutrición y dietética",
      "Gerontología y cuidados del mayor",
    ],
  },
  {
    code: "10",
    label: "Servicios",
    subareas: [
      "Turismo, hotelería y restauración",
      "Deporte y ciencias del deporte",
      "Peluquería, estética y bienestar",
      "Transporte y logística",
      "Seguridad y vigilancia",
      "Servicios comunitarios",
    ],
  },
] as const;

export type UnescoField = (typeof UNESCO_FIELDS)[number];
export type UnescoSubarea = UnescoField["subareas"][number];
